#!/bin/sh


echo "deploy: Installing deps"
if bundle install --path vendor/bundle; then
  jekyll="bundle exec jekyll"
else
  jekyll=jekyll
fi

set -o errexit

echo "deploy: Building site..."
$jekyll build
echo "deploy: Building site done."

echo "deploy: Updating website config..."
aws s3api put-bucket-website --bucket mixim-site --website-configuration file://website.json
echo "deploy: Updating website config done."

echo "deploy: Syncing files..."
# we use --delete to delete files in S3 that aren't present locally.
aws s3 sync _site s3://mixim-site --delete
echo "deploy: Syncing files done."

echo "deploy: Deploy complete."
