#!/bin/sh

set -o errexit

echo "deploy: Installing deps"
bundle install --path vendor/bundle

echo "deploy: Building site..."
bundle exec jekyll build
echo "deploy: Building site done."

echo "deploy: Updating website config..."
aws s3api put-bucket-website --bucket mixim-site --website-configuration file://website.json
echo "deploy: Updating website config done."

echo "deploy: Syncing files..."
# we use --delete to delete files in S3 that aren't present locally.
aws s3 sync _site s3://mixim-site --delete
echo "deploy: Syncing files done."

echo "deploy: Deploy complete."
